Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /dj-rest-auth/registration/account-confirm-email/<key>/
Bad Request: /dj-rest-auth/registration/account-confirm-email/<key>/
Watching for file changes with StatReloader
Disabling user: test
Internal Server Error: /dj-rest-auth/registration/account-confirm-email/NA:1tXGBw:lI-VzhrdeUMkGqA7rnjnEhnngam_ZVp-TQyj3QN-_rA/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 227, in get
    return self.render_to_response(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 200, in render_to_response
    template=self.get_template_names(),
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 212, in get_template_names
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: TemplateResponseMixin requires either a definition of 'template_name' or an implementation of 'get_template_names()'
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Bad Request: /dj-rest-auth/registration/account-confirm-email/<key>/
Disabling user: test
Internal Server Error: /dj-rest-auth/registration/account-confirm-email/NQ:1tXGPw:FGc29rgdrpuSHqQsZroQuFnIRbq6QfODoQeo7K0m7Ns/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 227, in get
    return self.render_to_response(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 200, in render_to_response
    template=self.get_template_names(),
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 212, in get_template_names
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: TemplateResponseMixin requires either a definition of 'template_name' or an implementation of 'get_template_names()'
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
Disabling user: test
Internal Server Error: /dj-rest-auth/registration/account-confirm-email/Ng:1tXGaD:rF04UgiAx9GKSos0gpAoal1LCOio0JJQdbJX1H62g-A/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 227, in get
    return self.render_to_response(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 200, in render_to_response
    template=self.get_template_names(),
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 212, in get_template_names
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: TemplateResponseMixin requires either a definition of 'template_name' or an implementation of 'get_template_names()'
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\signals.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /dj-rest-auth/registration/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 47, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 68, in create
    user = self.perform_create(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 84, in perform_create
    user = serializer.save(self.request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\serializers.py", line 279, in save
    setup_user_email(request, user, [])
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\utils.py", line 254, in setup_user_email
    assert not EmailAddress.objects.filter(user=user).exists()  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Internal Server Error: /dj-rest-auth/registration/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 47, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 68, in create
    user = self.perform_create(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 84, in perform_create
    user = serializer.save(self.request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\serializers.py", line 279, in save
    setup_user_email(request, user, [])
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\utils.py", line 254, in setup_user_email
    assert not EmailAddress.objects.filter(user=user).exists()  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Internal Server Error: /dj-rest-auth/registration/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 47, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 68, in create
    user = self.perform_create(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 84, in perform_create
    user = serializer.save(self.request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\serializers.py", line 279, in save
    setup_user_email(request, user, [])
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\utils.py", line 254, in setup_user_email
    assert not EmailAddress.objects.filter(user=user).exists()  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Bad Request: /dj-rest-auth/registration/
Internal Server Error: /dj-rest-auth/registration/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 47, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 68, in create
    user = self.perform_create(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 84, in perform_create
    user = serializer.save(self.request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\serializers.py", line 279, in save
    setup_user_email(request, user, [])
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\utils.py", line 254, in setup_user_email
    assert not EmailAddress.objects.filter(user=user).exists()  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /dj-rest-auth/registration/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 47, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 68, in create
    user = self.perform_create(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 84, in perform_create
    user = serializer.save(self.request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\serializers.py", line 279, in save
    setup_user_email(request, user, [])
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\utils.py", line 254, in setup_user_email
    assert not EmailAddress.objects.filter(user=user).exists()  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\signals.py changed, reloading.
Watching for file changes with StatReloader
Disabling user: test
Internal Server Error: /dj-rest-auth/registration/account-confirm-email/MTM:1tXHGG:EttA9jgEMXmN6aWTVgJ2qHhdreWlKCGJXdn0zzi0zog/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 227, in get
    return self.render_to_response(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 200, in render_to_response
    template=self.get_template_names(),
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 212, in get_template_names
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: TemplateResponseMixin requires either a definition of 'template_name' or an implementation of 'get_template_names()'
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /dj-rest-auth/registration/
Bad Request: /dj-rest-auth/registration/
Bad Request: /dj-rest-auth/registration/
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
Method Not Allowed: /dj-rest-auth/registration/
Disabling user: test
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
Disabling user: test
Disabling user: test
Disabling user: test
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Disabling user: test
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
Disabling user: test
Disabling user: test
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
Disabling user: Test
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
Disabling user: test
Not Found: /login
Not Found: /login
Internal Server Error: /dj-rest-auth/registration/account-confirm-email/MjI:1tXJoB:joirxFfdEkemAegB5zO-OtqauOHpceG2hH_r-oKZ02w/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py", line 28, in get
    confirmation = self.get_object()
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\views.py", line 300, in get_object
    raise Http404()
django.http.response.Http404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py", line 45, in get
    return render(request, self.template_name, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\base.py", line 573, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 9: 'static'. Did you forget to register or load this tag?
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /dj-rest-auth/registration/account-confirm-email/MjI:1tXJoB:joirxFfdEkemAegB5zO-OtqauOHpceG2hH_r-oKZ02w/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py", line 28, in get
    confirmation = self.get_object()
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\views.py", line 300, in get_object
    raise Http404()
django.http.response.Http404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py", line 45, in get
    return render(request, self.template_name, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\base.py", line 573, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 9: 'static'. Did you forget to register or load this tag?
Not Found: /login
Not Found: /login
